global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'fabric_peers'
    static_configs:
      - targets:
        - 'peer0.manufacturer.example.com:9443'
        - 'peer0.transporter.example.com:9443'
        - 'peer0.warehouse.example.com:9443'
        - 'peer0.retailer.example.com:9443'
    metrics_path: /metrics
    scheme: http

  - job_name: 'orderer'
    static_configs:
      - targets:
        - 'orderer.example.com:9443'
    metrics_path: /metrics
    scheme: http

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'localhost:9100'