name: build-and-test
on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: 
          go-version: '1.24'
      - run: go test ./chaincode/...
      
  build-images:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push peer image with chaincode
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.peer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/ship-peer:1.0
            ghcr.io/${{ github.repository }}/ship-peer:latest
      
      - name: Build and push listener image
        uses: docker/build-push-action@v5
        with:
          context: ./services/listener
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/listener:1.0
            ghcr.io/${{ github.repository }}/listener:latest
      
      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/app:1.0
            ghcr.io/${{ github.repository }}/app:latest